FROM ubuntu:24.04

# Set non-interactive frontend for apt
ENV DEBIAN_FRONTEND=noninteractive

ARG USER_UID=1001
ARG USER_GID=1001
ARG USERNAME=hadoop
ARG GROUPNAME=hadoop
ARG ARCH=arm64  # TODO automate

# Update and install core tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-17-jdk \
    maven \
    git \
    curl \
    wget \
    fd-find \
    tree \
    ripgrep \
    neovim \
    sudo \
    locales \
    less \
    unzip \
    build-essential \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Set up locale
RUN locale-gen en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Set JAVA_HOME
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-$ARCH
ENV PATH=$JAVA_HOME/bin:$PATH

# Set up a user for development (optional)
RUN groupadd --gid $USER_GID $GROUPNAME && \
    useradd --uid $USER_UID --gid $USER_GID --shell /bin/bash --create-home $USERNAME

RUN echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/hadoop
RUN mkdir -p /opt/hadoop
RUN chown -R $USERNAME:$GROUPNAME /opt/hadoop
USER $USERNAME
ENV HADOOP_HOME=/opt/hadoop
ENV PATH=$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$PATH

WORKDIR /home/$USERNAME

# Default shell
CMD ["/bin/bash"]
